version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    ports:
      - "3001:3001"
    restart: unless-stopped